nonpath ="F:/Research/Phosphorylation/prepareddata/combineddata/cdhit/nonphos.fasta"
moonpath = "F:/Research/Phosphorylation/prepareddata/combineddata/cdhit/phos.fasta"

non = ftrCOOL::AAKpartComposition(nonpath)
moon =ftrCOOL::AAKpartComposition(moonpath)
proteins = rbind(moon,non)
proteins = round(proteins,6)
#***********************************************************************************************************
non = ftrCOOL::SGAAC(nonpath,numNterm = 5)
moon =ftrCOOL::SGAAC(moonpath,numCterm = 5)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
#non = ftrCOOL::AAutoCor(nonpath)
#moon =ftrCOOL::AAutoCor(moonpath)
#p = rbind(moon,non)
#p = round(p,6)
#proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::CkSAApair(nonpath)
moon =ftrCOOL::CkSAApair(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::CkSGAApair(nonpath)
moon =ftrCOOL::CkSGAApair(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::CTD(nonpath)
moon =ftrCOOL::CTD(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::CTDC(nonpath)
moon =ftrCOOL::CTDC(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::CTDD(nonpath)
moon =ftrCOOL::CTDD(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::CTDT(nonpath)
moon =ftrCOOL::CTDT(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::DDE(nonpath)
moon =ftrCOOL::DDE(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::SGAAC(nonpath,numNterm = 5)
moon =ftrCOOL::SGAAC(moonpath,numCterm = 5)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::LocalPoSpKAAF(nonpath)
moon =ftrCOOL::LocalPoSpKAAF(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::EAAComposition(nonpath,winSize = 10)
moon =ftrCOOL::EAAComposition(moonpath,winSize = 10)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::EGAAComposition(nonpath,winSize = 5)
moon =ftrCOOL::EGAAComposition(moonpath,winSize = 5)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::ExpectedValueAA(nonpath)
moon =ftrCOOL::ExpectedValueAA(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::ExpectedValueGAA(nonpath)
moon =ftrCOOL::ExpectedValueGAA(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::ExpectedValueGKmerAA(nonpath)
moon =ftrCOOL::ExpectedValueGKmerAA(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::ExpectedValueKmerAA(nonpath)
moon =ftrCOOL::ExpectedValueKmerAA(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
#non = ftrCOOL::kGAAComposition(nonpath)
#moon =ftrCOOL::kGAAComposition(moonpath)
#p = rbind(moon,non)
#p = round(p,6)
#proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::GrpDDE(nonpath)
moon =ftrCOOL::GrpDDE(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::SAAC(nonpath)
moon =ftrCOOL::SAAC(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::QSOrder(nonpath)
moon =ftrCOOL::QSOrder(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::SOCNumber(nonpath)
moon =ftrCOOL::SOCNumber(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::PseKRAAC_T1(nonpath)
moon =ftrCOOL::PseKRAAC_T1(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::PseKRAAC_T2(nonpath)
moon =ftrCOOL::PseKRAAC_T2(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::PseKRAAC_T3A(nonpath)
moon =ftrCOOL::PseKRAAC_T3A(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::PseKRAAC_T3B(nonpath)
moon =ftrCOOL::PseKRAAC_T3B(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
#non = ftrCOOL::PseKRAAC_T4(nonpath)
#moon =ftrCOOL::PseKRAAC_T4(moonpath)
#p = rbind(moon,non)
#p = round(p,6)
#proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::PseKRAAC_T5(nonpath)
moon =ftrCOOL::PseKRAAC_T5(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::PseKRAAC_T6A(nonpath)
moon =ftrCOOL::PseKRAAC_T6A(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::PseKRAAC_T6B(nonpath)
moon =ftrCOOL::PseKRAAC_T6B(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::PseKRAAC_T7(nonpath)
moon =ftrCOOL::PseKRAAC_T7(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::PseKRAAC_T8(nonpath)
moon =ftrCOOL::PseKRAAC_T8(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::PseKRAAC_T9(nonpath)
moon =ftrCOOL::PseKRAAC_T9(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
#non = ftrCOOL::PseKRAAC_T10(nonpath)
#moon =ftrCOOL::PseKRAAC_T10(moonpath)
#p = rbind(moon,non)
#p = round(p,6)
#proteins = cbind(proteins,p)
#***********************************************************************************************************
#non = ftrCOOL::PseKRAAC_T11(nonpath)
#moon =ftrCOOL::PseKRAAC_T11(moonpath)
#p = rbind(moon,non)
#p = round(p,6)
#proteins = cbind(proteins,p)
#***********************************************************************************************************
#non = ftrCOOL::PseKRAAC_T12(nonpath)
#moon =ftrCOOL::PseKRAAC_T12(moonpath)
#p = rbind(moon,non)
#p = round(p,6)
#proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::PseKRAAC_T13(nonpath)
moon =ftrCOOL::PseKRAAC_T13(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::PseKRAAC_T14(nonpath)
moon =ftrCOOL::PseKRAAC_T14(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::PseKRAAC_T15(nonpath)
moon =ftrCOOL::PseKRAAC_T15(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)
#***********************************************************************************************************
non = ftrCOOL::PseKRAAC_T16(nonpath)
moon =ftrCOOL::PseKRAAC_T16(moonpath)
p = rbind(moon,non)
p = round(p,6)
proteins = cbind(proteins,p)


class0 = matrix (0,nrow(non),1)
class1 = matrix (1,nrow(moon),1)
class = rbind(class0,class1)
proteins = cbind(proteins,class)
write.csv(proteins,"F:/Research/Phosphorylation/R/result/All_reduced.csv",row.names = TRUE)

